### ISSUE TITLE
Failed installnative on Windows does not leave power shell window open

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#657]
Related to #656 - user said in Riot that

> ok, Im just trying to figure out a way to make powershell not close after running the script so i can read the output

Permalink https://matrix.to/#/!xmubtggllUtLrQiGyn:matrix.org/%2415283898804338516FQCyr:matrix.org

**Comment by budomino** [comment]
OK So after trying to figure out why I also had this problem, I realized the real problem is that there's no error message to let you know you need Python3 installed. After I installed python3 via Chocolatey the process completed without a hitch.

**Comment by bovine3dom** [comment]
There is an error message, you just can't see it because the window closes :(

**Comment by dokpm0** [comment]
I tried installing Python3.  It didn't help me.  If I issue $host.enternestedprompt() before trying to install native it leaves the PowerShell window open so I can see the error.  With or without python I always get a download failed, quitting error.  Yet I can manually download what PowerShell fails to download.  Is there a way to install native without using PowerShell?

**Comment by bovine3dom** [comment]
You have to set some registry keys, so it's a bit of a faff.

I suggest downloading the files that the PowerShell script uses and then editing the script to use your local files, and then running that.

Could you copy and paste the errors here?

**Comment by bovine3dom** [comment]
@gsbabil regarding this issue (PowerShell not remaining open), do you have any ideas?

**Comment by dokpm0** [comment]
This is what I'm getting:

Select-Object : Property "Source" cannot be found.
At line:499 char:28
+             | Select-Object <<<<  -ExpandProperty "Source"
    + CategoryInfo          : InvalidArgument: (py.exe:PSObject) [Select-Object], PSArgumentException
    + FullyQualifiedErrorId : ExpandPropertyNotFound,Microsoft.PowerShell.Commands.SelectObjectCommand

    - Python 3 found at:
[+] Preparing C:\Users\dokpm0\.tridactyl ...
    - C:\Users\dokpm0\.tridactyl exists, moving on ...
    - Testing C:\Users\dokpm0\.tridactyl was successful!
    - Creating C:\Users\dokpm0\.tridactyl was successful!
[+] Downloading https://raw.githubusercontent.com/cmcaine/tridactyl/master/native/native_main.py?1531167545.20697 ...
Invoke-WebRequest StatusCode:
Invoke-WebRequest StatusDescription:
[+] Downloading failed, quitting ...

I'm a little out of my element with PowerShell.  I'm a Linux guy, but forced to use Windows at work.

**Comment by gsbabil** [comment]
@dokpm0 @bovine3dom

The error seems to be here: `Python 3 found at:`, which stems from here `InvalidArgument: (py.exe:PSObject)`.

If you open PowerShell on your machine and run the following, what do you get?

```Powershell
py -3 -u -c "import sys; print(sys.version)"
```

Following is my output:

```Powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Loading personal and system profiles took 820ms.
C:\Users\<user>
> py -3 -u -c "import sys; print(sys.version)"
3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)]
C:\Users\<user>
>
```

In short, for some reason, Python is not found on @dokpm0 's system, but `win_install.ps1` thinks it was found. There's a potential bug hiding there. We need to know what triggers it to come up with a fix. In other words, I'd like to reproduce it! 😃 

Hope this helps. Thanks.

_P.S._

```
Invoke-WebRequest StatusCode:
Invoke-WebRequest StatusDescription:
```

Also, I don't yet know what caused the failed download of `native_main.py` here. The URL above is valid.

**Comment by bovine3dom** [comment]
@gsbabil thanks. Do you have any idea why the PowerShell window closes if the script fails?

**Comment by dokpm0** [comment]
I get:

Windows PowerShell
Copyright (C) 2009 Microsoft Corporation. All rights reserved.

PS C:\Users\<user> py -3 -u -c "import sys; print(sys.version)"
3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
PS C:\Users\<user>

Without python installed I was getting a similar download error trying to install the non-python installer, which I could download manually.

**Comment by dokpm0** [comment]
That should have been trying to download the non-python installer.

**Comment by gsbabil** [comment]
@bovine3dom 

> Do you have any idea why the PowerShell window closes if the script fails?

No. 

It could be one of the `exit -1`s, but they should really only `exit` the `win_install.ps1` _script_, not the parent _shell_.

@dokpm0 

Since you seem to have Python and `py`, the following should really have _not_ failed, but it seems that it does on your system:

```
Get-Command "py" | Select-Object -ExpandProperty "Source"
```

1. Could you please open a PowerShell instance, run the command above and share the output. It should give you something like `C:\Windows\py.exe`.

2. Also, could you please manually download the `win_install.ps1` from [here][0], save it on your desktop, open a PowerShell instance, run `powershell ~/Desktop/win_install.ps1` and share the output?

Thanks.

[0]: https://raw.githubusercontent.com/cmcaine/tridactyl/master/native/win_install.ps1

**Comment by gsbabil** [comment]
@bovine3dom @dokpm0 

```
[+] Preparing C:\Users\dokpm0.tridactyl ...
```

Not sure if the above was due to typo, but there needs a `\` before `.tridactyl` above. Something like the following. The lack of the `\` is probably causing the download to fail.

```
[+] Preparing C:\Users\<user>\.tridactyl ...
```

Thanks.

**Comment by dokpm0** [comment]
I will try the above and post the results when I get back to work tomorrow.

**Comment by Bzly** [comment]
@bovine3dom Are the registry keys the only reason you're doing it in PS and not batch? Setting registry keys in batch isn't particularly difficult, probably less so than all this faf.

**Comment by gsbabil** [comment]
@bovine3dom @dokpm0 

PowerShell may auto-close in the following scenarios. I'm not sure if you are using any of these:

1. Right-click on `win_install.ps1` > select `Run with PowerShell`
2. Start-button > Run or `Win+R` > `powershell "Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/cmcaine/tridactyl/master/native/win_install.ps1'))"`

I can not reproduce PowerShell window auto-close by doing the following. Could you please confirm that PowerShell auto-closes if you do the following?

1. In Firefox > Tridactyl command-bar, run `:installnative`
    - PowerShell command [0] is copied to clipboard
2. Open a fresh PowerShell console
3. Press `Ctrl+V`  > press `Enter`

Thanks.

[0] `Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/cmcaine/tridactyl/master/native/win_install.ps1'))`

**Comment by dokpm0** [comment]
Babil,

On Mon, Jul 09, 2018 at 02:23:29PM -0700, Babil Golam Sarwar wrote:
 
> Get-Command "py" | Select-Object -ExpandProperty "Source"
>
> 1. Could you please open a PowerShell instance, run the command above and
> share the output. It should give you something like `C:\Windows\py.exe`.

The ability to copy/paste to/from a PowerShell session seems to be hit or
miss on my PC.  I can only past into a PowerShell session by right clicking,
and can't seem to copy PowerShell output this morning.  This would be so
much easier if it could be done via an MSYS2 bash session.

I get the same error when I issue the above command directly, Select-Object
: Property "Source" cannot be found.

> 2. Also, could you please manually download the `win_install.ps1` from
> [here][0], save it on your desktop, open a PowerShell instance, run
> `powershell ~/Desktop/win_install.ps1` and share the output?

It tells me the file cannot be loaded because it's not digitally signed.



-- 

Kevin
http://www.RawFedDogs.net
http://www.Lassie.xyz
http://www.WacoAgilityGroup.org
Bruceville, TX

What's the definition of a legacy system? One that works!
Errare humanum est, ignoscere caninum.

**Comment by bovine3dom** [comment]
> I can not reproduce PowerShell window auto-close by doing the following. Could you please confirm that PowerShell auto-closes if you do the following?
> 
> - In Firefox > Tridactyl command-bar, run :installnative
>     - PowerShell command [0] is copied to clipboard
> - Open a fresh PowerShell console
> - Press Ctrl+V > press Enter

Yes, it does, but only in some circumstances. Steps to reproduce:

1. Rename C:\Windows\py.exe to something else
2. Run the install native command in a powershell window and watch as it exits after it fails to find python

The window stays open if instead the internet is disconnected, or if it succeeds.

**Comment by gsbabil** [comment]
@bovine3dom

>> I can not reproduce PowerShell window auto-close by doing the
>> following. Could you please confirm that PowerShell auto-closes if
>> you do the following?
>>
>>   - In Firefox > Tridactyl command-bar, run :installnative
>>       - PowerShell command [0] is copied to clipboard
>>   - Open a fresh PowerShell console
>>   - Press Ctrl+V > press Enter

> Yes, it does, but only in some circumstances. Steps to reproduce:

> Rename C:\Windows\py.exe to something else
> Run the install native command in a powershell window and watch as
> it exits after it fails to find python

Following your steps above (rename `py.exe` to something else), I
can get to the download fail issue, which I'm investigating right
now and will submit a patch shortly as applicable.

However my parent PowerShell window does _not_ close as you hint
above. It says open, and I get the following output. To confirm, were
you able to get to the PowerShell-auto-close symptom by following
the steps above?

Thanks.

#### ## After renaming `py.exe -> py.exe.bak`

```PowerShell
> PS C:\Users\username> Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.co
> m/cmcaine/tridactyl/master/native/win_install.ps1'))
> [+] Looking for Python 3 ...
>     - Python 3 not found, will use EXE ...
> [+] Preparing C:\Users\username\.tridactyl ...
>     - C:\Users\username\.tridactyl exists, moving on ...
>     - Testing C:\Users\username\.tridactyl was successful!
>     - Creating C:\Users\username\.tridactyl was successful!
> [+] Downloading https://tridactyl.cmcaine.co.uk/betas/native_main.exe ...
> Invoke-WebRequest StatusCode:
> Invoke-WebRequest StatusDescription:
> [+] Downloading failed, quitting ...
```

**Comment by gsbabil** [comment]
@bovine3dom @dokpm0

So as I see it right now, we have two potential issues:

1. PowerShell window auto-close
    - I need more directions to reproduce this

2. Download failure
    - I _can_ reproduce this and will submit a patch soon as applicable

    - Note that in absence of `py.exe`, Python 3 detection fails
      on my system, and the downloading falls back to
      `native_main.exe`. This I think was not the case for
      @dokpm0, which might be something else. I don't think @dokpm0
      has `py.exe` on his system. Could you please confirm with the
      following?

```PowerShell
PS C:\Users\username> Get-Command 'py.exe'
```

**Comment by gsbabil** [comment]
@bovine3dom @dokpm0

#### ## Notes on `py.exe`

- We depend on ["Python Launcher for Windows"][0] to run our
  Python-3 scripts on Windows.

    - This is because, unlike on traditional Unix systems, Python on
      Windows does not come with `python` for Python-2, and
      `python3` for Python-3. So a shebang like "/usr/bin/env
      python3" does not work on Windows. Also, default handlers for
      Python scripts on Windows may have an IDE or editor set to
      open them. Hence we need something like `py -3 -u`.

    - Having "Python Launcher for Windows" installed will usually
      leave `py.exe` in `$env:WINDIR` _e.g._ `C:\Windows`

        - BTW, ["Python Launcher for Windows"] has an official PEP
          ([PEP 397][0]), is part of the official distribution found
          on [Python.org][1]. So we are within the boundaries of the
          standard, and can advice Tridactyl users on Windows
          accordingly.

- `native_main.py` should run with any Python-3 distributions
  shipping Python 3.5-3.7, however on Windows the test is done with
  the standard distribution from Python.org, and we need `py.exe` to
  invoke `native_main.py`. This is because of the reason explained
  above. So please make sure your system has `py.exe` if Python
  installed.

    - @bovine3dom this might remind you an older conversation where
      I suggested that we install `native_main.exe` on Windows as
      the default installation action, irrespective of Python being
      available on the target Windows system :-), unless the user
      invoked the PS script with something like `-HasPython`

- A quick way to have Python-3 installed on a Windows system
  with PowerShell is via [Chocolatey][2]. Once Chocolatey is
  installed, the following should have you sorted:

  ```PowerShell
  PS C:\Users\username> choco install python3
  ```

Hope this helps. Thanks.

[0]: https://www.python.org/dev/peps/pep-0397
[1]: https://www.python.org/
[2]: https://chocolatey.org/

**Comment by gsbabil** [comment]
@dokpm0

> I get the same error when I issue the above command directly,
> Select-Object : Property "Source" cannot be found.

This means that you most likely don't have `py.exe` on your system,
in which case the `win_install.ps1` should have fallen back to
`native_main.exe`, which it does for me (see my comments above to
@bovine3dom). Could you please give the follow another go:

```PowerShell
PS C:\Users\username> Get-Command 'py.exe'
```

However, there seems to be a bug around downloading
`native_main.exe` in absence of Python. I'm currently looking into
it, and will submit a patch shortly.

> The ability to copy/paste to/from a PowerShell session seems to be
> hit or miss on my PC.

Pasting via right-click is fine.

> This would be so much easier if it could be done via an MSYS2 bash
> session.

Agreed. The current development on Windows is indeed primarily
Cygwin or MSYS2 based. You can by the way run PowerShell from inside
MinTTY (MSYS2 shell). Both of these should also work from within
`cmd.exe`.

```Bash
  $  powershell -NonInteractive -NoProfile -InputFormat None -ExecutionPolicy Bypass ~/Desktop/win_install.ps1
```

Or,

```Bash
$ powershell -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None -Command "Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/cmcaine/tridactyl/master/native/win_install.ps1'))"
```

Our rationale for PowerShell was that it seems to be widely
available on all latest Windows systems, and we don't want to force
users without MSYS2 to install it as another Tridactyl dependency.

In your initial attempt, `win_install.ps1` should really have
detected that you don't have Python on your system, and fallen back
to installing `native_main.exe`. As said, there seems to be a bug
around downloading `native_main.exe` right now. I will try to submit
a patch ASAP. In the meantime, please consider using the beta builds
from [here][0].

Thank you.

[0]: https://tridactyl.cmcaine.co.uk/betas/?sort=time&order=desc

**Comment by gsbabil** [comment]
@bovine3dom @dokpm0

Downloading `native_main.exe` fails due to TLS version mismatch. I'm
quite positive that this was not the case when I first submitted the
`native_main.exe` support. Following is the actual exception:

```PowerShell
Invoke-WebRequest : The request was aborted: Could not create SSL/TLS secure channel.
At line:1 char:1
+ Invoke-WebRequest -Uri https://tridactyl.cmcaine.co.uk/betas/native_m ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

In summary, PowerShell by default tends to support `SSLv3` and
`TLS-1.0` only, but `tridactyl.cmcaine.co.uk` currently only
supports the following (selected TLS-1.1 and TLS-1.2 ciphers only).
The server change must have happened rather recently.

I'll submit a PR soon to fix this. Thank you.

```
[+] tridactyl.cmcaine.co.uk:443 supports the following:

  [01] - tls1_1:ECDHE-RSA-AES256-SHA
  [02] - tls1_1:ECDHE-RSA-AES128-SHA
  [03] - tls1_1:AES256-SHA
  [04] - tls1_1:AES128-SHA
  [05] - tls1_2:ECDHE-RSA-AES256-GCM-SHA384
  [06] - tls1_2:ECDHE-RSA-CHACHA20-POLY1305
  [07] - tls1_2:ECDHE-RSA-AES128-GCM-SHA256
  [08] - tls1_2:ECDHE-RSA-AES256-SHA
  [09] - tls1_2:ECDHE-RSA-AES128-SHA
  [10] - tls1_2:AES256-SHA
  [11] - tls1_2:AES128-SHA
```

_P.S._

@bovine3dom

Since you are using [Caddy][0], it's possible that Caddy
automatically upgraded to a stronger TLS certificate from Let's
Encrypt.

It's good that we are using strong TLS ciphers on the server. My two
cents would be that we drop `AES256-SHA` and `AES128-SHA` from both
TLS-1.1 and TLS-1.2 if you care.

Thanks.


[0]: https://caddyserver.com

**Comment by gsbabil** [comment]
@dokpm0 

I just submitted #786 which should fix the download and auto-close issues being discussed above, and would also allow the output of `:installnative` to go into any of the following shells:

- MinTTY/MSYS2
- Windows Command Prompt (`cmd.exe`)
- Windows PowerShell (`powershell.exe`)
- Cygwin

Please give the beta builds a go when you can. Thanks!

**Comment by bovine3dom** [comment]
Fixed in #786. Thanks @gsbabil!

**Comment by dokpm0** [comment]
Babil,

On Tue, Jul 10, 2018 at 04:35:46PM -0700, Babil Golam Sarwar wrote:

> So please make sure your system has `py.exe` if Python installed.

Yes, I do have py.exe in C:\Windows.  py --version from an MSYS2 bash shell
shows I have version 3.7.0.




-- 

Kevin
http://www.RawFedDogs.net
http://www.Lassie.xyz
http://www.WacoAgilityGroup.org
Bruceville, TX

What's the definition of a legacy system? One that works!
Errare humanum est, ignoscere caninum.

**Comment by bovine3dom** [comment]
@dokpm0, would you mind making another issue about your problem? This one was for the closing window which has been fixed and I think trying to fix your one here will confuse things.

**Comment by dokpm0** [comment]
Babil,

On Tue, Jul 10, 2018 at 07:57:31PM -0700, Babil Golam Sarwar wrote:
 
> I just submitted #786 which should fix the download and auto-close issues
> being discussed above, and would also allow the output of `:installnative`
> to go into any of the following shells:
> 
> - MinTTY/MSYS2
> - Windows Command Prompt (`cmd.exe`)
> - Windows PowerShell (`powershell.exe`)
> - Cygwin

Great!!

> Please give the beta builds a go when you can. Thanks!

With the latest beta build when I try to :installnative I get a 404 not
found error.  Changing win_install.ps1 to install.ps1 in the URL
:installnative copied to the clipboard I still encountered the python issue
my PC has.  I tried uninstalling python to force the installer to switch to
the native_main.exe installer.  I then got an "'Invoke-WebRequest' is not
recognized as the name of a cmdlet" error.  It looks like the root of my
problems might be that PowerShell on my PC is still at the 2.x version
level.  I'm trying to see if I can update it.




-- 

Kevin
http://www.RawFedDogs.net
http://www.Lassie.xyz
http://www.WacoAgilityGroup.org
Bruceville, TX

What's the definition of a legacy system? One that works!
Errare humanum est, ignoscere caninum.

**Comment by dokpm0** [comment]
Oliver,

On Wed, Jul 11, 2018 at 07:55:27AM -0700, Oliver Blanthorn wrote:

> @dokpm0, would you mind making another issue about your problem? This one
> was for the closing window which has been fixed and I think trying to fix
> your one here will confuse things.

There's no need for another issue.  It looks like the root of my problem was
I was running PowerShell version 2.x.  After upgrading PowerShell I was able
to install native.  I first tried installing it without Python.  The native
installer said the installation was successful, but :native said native
wasn't installed.  So I installed python and tried installing it via the
python installer.  Now :native detects native!!!




-- 

Kevin
http://www.RawFedDogs.net
http://www.Lassie.xyz
http://www.WacoAgilityGroup.org
Bruceville, TX

What's the definition of a legacy system? One that works!
Errare humanum est, ignoscere caninum.
